package com.gemini.java_practice.io;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class LogFileCreation {
//  Code to generate a 1000 line input file with 2 columns: website name and http status code
    public static void main(String[] args) {
       

            List<String> websites = new ArrayList<>();
            websites.add("google.com");
            websites.add("youtube.com");
            websites.add("facebook.com");
            websites.add("baidu.com");
            websites.add("wikipedia.org");
            websites.add("yahoo.com");
            websites.add("google.co.in");
            websites.add("amazon.com");
            websites.add("qq.com");
            websites.add("google.co.jp");
            websites.add("live.com");
            websites.add("taobao.com");
            websites.add("vk.com");
            websites.add("twitter.com");
            websites.add("instagram.com");
            websites.add("hao123.com");
            websites.add("sohu.com");
            websites.add("sina.com.cn");
            websites.add("reddit.com");
            websites.add("google.de");
            websites.add("linkedin.com");
            websites.add("tmall.com");
            websites.add("yahoo.co.jp");
            websites.add("weibo.com");
            websites.add("google.fr");
            websites.add("360.cn");
            websites.add("google.co.uk");
            websites.add("google.ru");
            websites.add("google.com.br");
            websites.add("yandex.ru");
            websites.add("ebay.com");
            websites.add("bing.com");
            websites.add("msn.com");
            websites.add("google.it");
            websites.add("soso.com");
            websites.add("t.co");
            websites.add("wordpress.com");
            websites.add("google.es");
            websites.add("microsoft.com");
            websites.add("tumblr.com");
            websites.add("aliexpress.com");
            websites.add("blogspot.com");
            websites.add("netflix.com");
            websites.add("amazon.co.jp");
            websites.add("ok.ru");
            websites.add("google.com.hk");
            websites.add("stackoverflow.com");
            websites.add("google.ca");
            websites.add("google.com.mx");
            websites.add("imgur.com");
            websites.add("pornhub.com");
            websites.add("apple.com");
            websites.add("Naver.com");
            websites.add("mail.ru");
            websites.add("imdb.com");
            websites.add("popads.net");
            websites.add("onclickads.net");
            websites.add("office.com");
            websites.add("google.co.kr");
            websites.add("github.com");
            websites.add("pinterest.com");
            websites.add("paypal.com");
            websites.add("tianya.cn");
            websites.add("google.com.tw");
            websites.add("google.com.tr");
            websites.add("google.com.au");
            websites.add("diply.com");
            websites.add("amazon.de");
            websites.add("google.co.id");
            websites.add("microsoftonline.com");
            websites.add("onclckds.com");
            websites.add("twitch.tv");
            websites.add("adobe.com");
            websites.add("txxx.com");
            websites.add("amazon.co.uk");
            websites.add("wikia.com");
            websites.add("cnzz.com");
            websites.add("coccoc.com");
            websites.add("so.com");
            websites.add("xhamster.com");
            websites.add("fc2.com");
            websites.add("pixnet.net");
            websites.add("dropbox.com");
            websites.add("google.pl");
            websites.add("adf.ly");
            websites.add("zhihu.com");
            websites.add("whatsapp.com");
            websites.add("googleusercontent.com");
            websites.add("alibaba.com");
            websites.add("bongacams.com");
            websites.add("ask.com");
            websites.add("google.com.eg");
            websites.add("google.com.sa");
            websites.add("google.co.th");
            websites.add("bbc.com");
            websites.add("youth.cn");
            websites.add("savefrom.net");
            websites.add("amazon.in");
            websites.add("gmw.cn");
            websites.add("google.com.ar");
            websites.add("bbc.co.uk");
            websites.add("nytimes.com");
            websites.add("rakuten.co.jp");
            websites.add("nicovideo.jp");
            websites.add("espn.com");
            websites.add("cnn.com");
            websites.add("craigslist.org");
            websites.add("xvideos.com");
            websites.add("booking.com");
            websites.add("google.nl");
            websites.add("ebay.co.uk");
            websites.add("uol.com.br");
            websites.add("walmart.com");
            websites.add("dailymail.co.uk");
            websites.add("globo.com");
            websites.add("avito.ru");
            websites.add("google.com.vn");
            websites.add("google.com.co");
            websites.add("google.com.ph");
            websites.add("google.com.ua");
            websites.add("redtube.com");
            websites.add("doubleclick.net");
            websites.add("xnxx.com");
            websites.add("samsung.com");
            websites.add("accuweather.com");
            websites.add("googleadservices.com");
            websites.add("googleweblight.com");
            websites.add("kat.cr");
            websites.add("onet.pl");
            websites.add("answers.yahoo.com");
            websites.add("news.yahoo.co.jp");
            websites.add("news.google.com");
            websites.add("Bit.ly");

            List<Integer> errorCodes = new ArrayList<>();
            errorCodes.add(100);
            errorCodes.add(101);
            errorCodes.add(102);
            errorCodes.add(200);
            errorCodes.add(201);
            errorCodes.add(202);
            errorCodes.add(203);
            errorCodes.add(204);
            errorCodes.add(205);
            errorCodes.add(206);
            errorCodes.add(207);
            errorCodes.add(208);
            errorCodes.add(226);
            errorCodes.add(300);
            errorCodes.add(301);
            errorCodes.add(302);
            errorCodes.add(303);
            errorCodes.add(304);
            errorCodes.add(305);
            errorCodes.add(307);
            errorCodes.add(308);
            errorCodes.add(400);
            errorCodes.add(401);
            errorCodes.add(402);
            errorCodes.add(403);
            errorCodes.add(404);
            errorCodes.add(405);
            errorCodes.add(406);
            errorCodes.add(407);
            errorCodes.add(408);
            errorCodes.add(409);
            errorCodes.add(410);
            errorCodes.add(411);
            errorCodes.add(412);
            errorCodes.add(413);
            errorCodes.add(414);
            errorCodes.add(415);
            errorCodes.add(416);
            errorCodes.add(417);
            errorCodes.add(418);
            errorCodes.add(421);
            errorCodes.add(422);
            errorCodes.add(423);
            errorCodes.add(424);
            errorCodes.add(426);
            errorCodes.add(428);
            errorCodes.add(429);
            errorCodes.add(431);
            errorCodes.add(444);
            errorCodes.add(451);
            errorCodes.add(499);
            errorCodes.add(500);
            errorCodes.add(501);
            errorCodes.add(502);
            errorCodes.add(503);
            errorCodes.add(504);
            errorCodes.add(505);
            errorCodes.add(506);
            errorCodes.add(507);
            errorCodes.add(508);
            errorCodes.add(510);
            errorCodes.add(511);
            errorCodes.add(599);

            for (int i = 0; i < 1000; i++) {
                int websiteIndex = getRandom(websites.size());
                int errorCodesIndex = getRandom(errorCodes.size());

                String website = websites.get(websiteIndex);
                Integer errorCode = errorCodes.get(errorCodesIndex);

                String line = String.format("%s\t%s", website, errorCode);
                System.out.println(line);
            }
        }

        private static int getRandom(int bound) {
            return new Random().nextInt(bound);
        }

    }

